version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - copyloopvar
    - goconst
    - gocritic
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    gosec:
      excludes:
        - G204 # subprocess launched with variable - git commands
        - G301 # directory permissions 0755 are standard and appropriate
        - G304 # file operations with user paths are the tool's purpose
        - G703 # path traversal - validating user paths is the tool's purpose
        - G706 # log injection - logging environment variables
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    rules:
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - errcheck
        path: _test\.go
        text: Error return value of `os.RemoveAll` is not checked
      - linters:
          - errcheck
        path: _test\.go
        text: Error return value of `cleanup` is not checked
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/andornaut/gog)
