run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - unparam
    - gofmt
    - goimports
    - gci
    - gosec
    - revive
    - misspell
    - unconvert
    - goconst
    - copyloopvar
    - bodyclose
    - gocritic

linters-settings:
  gci:
    sections:
      - standard # Standard library
      - default  # Third-party packages
      - prefix(github.com/andornaut/gog) # Local packages
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    rules:
      - name: exported
        disabled: true
  gosec:
    excludes:
      - G301 # directory permissions 0755 are standard and appropriate
      - G304 # file operations with user paths are the tool's purpose

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude gosec checks in test files
    - path: _test\.go
      linters:
        - gosec
    # Exclude errcheck for os.RemoveAll in defer statements in test files
    - path: _test\.go
      text: "Error return value of `os.RemoveAll` is not checked"
      linters:
        - errcheck
    # Exclude errcheck for cleanup() functions in test files
    - path: _test\.go
      text: "Error return value of `cleanup` is not checked"
      linters:
        - errcheck
